# Generated by Django 5.2.6 on 2025-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='created_at',
            field=models.DateField(),
        ),
    ]
